// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/qcpm-carolina/CarolinaGold.tsx": () => import("../components/mockups/qcpm-carolina/CarolinaGold.tsx"),
  "./components/mockups/qcpm-midnight/MidnightPrestige.tsx": () => import("../components/mockups/qcpm-midnight/MidnightPrestige.tsx"),
  "./components/mockups/qcpm-modern/ModernQueenCity.tsx": () => import("../components/mockups/qcpm-modern/ModernQueenCity.tsx"),
  "./components/mockups/qcpm-royal/RoyalHeritage.tsx": () => import("../components/mockups/qcpm-royal/RoyalHeritage.tsx")
};
